# Generated by Django 5.2.9 on 2025-12-31 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic_signs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_image_url', models.URLField()),
                ('ouput_image_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounding_box', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recognition.recognitionhistory')),
                ('traffic_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_signs.trafficsign')),
            ],
        ),
    ]
