# Generated by Django 5.2.9 on 2026-01-06 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0001_initial'),
        ('traffic_signs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recognitionresult',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recognition.recognitionhistory'),
        ),
        migrations.AddField(
            model_name='recognitionresult',
            name='traffic_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_signs.trafficsign'),
        ),
    ]
