# Generated by Django 5.2.9 on 2026-01-16 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0001_initial'),
        ('traffic_signs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectedsign',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_signs', to='recognition.detection'),
        ),
        migrations.AddField(
            model_name='recognitionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recognitionresult',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recognition.recognitionhistory'),
        ),
        migrations.AddField(
            model_name='recognitionresult',
            name='traffic_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_signs.trafficsign'),
        ),
        migrations.AddIndex(
            model_name='detectedsign',
            index=models.Index(fields=['detection', 'start_time'], name='recognition_detecti_1c5368_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedsign',
            index=models.Index(fields=['traffic_sign'], name='recognition_traffic_35fc18_idx'),
        ),
    ]
