# Generated by Django 5.2.9 on 2026-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_signs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsign',
            name='model_class_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
