# Generated by Django 5.2.9 on 2026-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_signs", "0002_trafficsign_model_class_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficsign",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
